export const hiddenAccounts = new Set([
  "aaronjmars",
  "bilion1983",
  "boredapeyc",
  "davestacey",
  "donofbase",
  "hackernoon",
  "infoinvt",
  "johannkerbrat",
  "jpfraneto",
  "sergeynazarovx",
  "mrsdoodlifts",
  "swenchan",
  "tmoney_145",
  "troll_",
  "vladtenev",
  "huawei",
  "tencentglobal",
  "bydcompany",
  "djiglobal",
  "autodesk",
  "imperialcollege",
  "spacex",
  "ethglobal",
  "uniswapbuilders",
  "mixpanel",
  "relayprotocol",
  "aztecfnd",
  "gopoversight",
  "fxshaw",
  "0x02yang",
  "0xjoeylau",
  "alifarhat79",
  "avhidotsol",
  "btcc_classic_kol",
  "boredapeyc",
  "calicomeepcat",
  "chadmasterxbt",
  "chrissmiiic",
  "citadelxbt",
  "cultureanon",
  "dacrooter",
  "damian_et",
  "devrel_virtuals",
  "doodles",
  "echanecashgirl",
  "esotericpigeon",
  "frankdegods",
  "heeyeosohot",
  "jiaa770",
  "joeyy_0x",
  "kashkysh",
  "kirabuilds",
  "kitonbill",
  "langerius",
  "lynnchu26",
  "mcglive",
  "meepcat_sol",
  "mehdi_scalify",
  "midjourney",
  "opnetoshi",
  "polymarket",
  "polymarketsport",
  "prmrsamm",
  "rohanbchopra",
  "rottcrypto",
  "sei_fnd",
  "seinetwork",
  "shawthread",
  "strangersolemn",
  "suifoundation",
  "suinetwork",
  "theewanseffect",
  "uniswap",
  "untaxxable",
  "wesley_wlowry85",
  "zengjiajun_eth",
  "zhuifei008",
]);

export const hiddenWords = [
  "founder",
  "ceo",
  "co-founder",
  "engineer",
  "attorney",
  "advisor",
  "investor",
  "teacher",
  "university",
  "official twitter",
  "support",
  "photographer",
  "marketing",
  "personal",
  "kol",
  "influencer",
  "official",
  "retail investor",
  "svp",
  "gm of",
  "tweets are my own",
  "bitcoin maxi",
  "learn any technology",
  "monthly readers",
  "where 50k",
  "alpha hunter",
  "alpha content",
  "apac social media",
  "ambassador",
  "building @",
  "cofounder",
  "comms",
  "communications",
  "community",
  "content",
  "devrel",
  "diluting the alpha",
  "foundation",
  "hunting @",
  "lead @",
  "lead ",
  "media",
  "m.s. student",
  "official account",
  "parody",
  "research lab",
  "sales bot",
  "student",
  "trader",
  "ventures",
];

export const hardHiddenWords = [
  "aztec foundation",
  "bitcoin-classic",
  "bored ape",
  "communications team",
  "ethereum's vision",
  "high-performance blockchain",
  "midjourney",
  "polymarket",
  "research lab",
  "sui foundation",
  "sui network",
  "sei network",
  "uniswap developers",
  "成熟",
  "公链",
  "基金会",
  "官方账号",
  "通讯团队",
  "研究实验室",
  "高性能区块链",
  "首席执行官",
  "联合创始人",
];

export const positiveWords = [
  "agent",
  "agents",
  "payment",
  "payments",
  "v4",
  "hook",
  "hooks",
  "launchpad",
  "onchain",
  "on-chain",
  "solana",
  "base",
  "bitcoin l1",
  "mmo",
  "game",
  "protocol",
  "infra",
  "infrastructure",
  "stablecoin",
  "perp",
  "market",
  "markets",
  "zk",
  "privacy",
  "defai",
  "robot",
  "robotics",
  "vault",
  "vaults",
  "creator vault",
  "nft collection",
  "marketplace",
  "uniswap",
  "token",
  "tokens",
  "ai native",
  "city builder",
  "city-builder",
  "dex",
  "free mint",
  "liquidity",
  "mint",
  "nft",
  "nfts",
  "oracle",
  "worlds built",
];

export function keyAccount(account) {
  return String(account || "").replace(/^@/, "").trim().toLowerCase();
}

export function isLikelyProject({ account = "", project = "", text = "", strongSignal = false } = {}) {
  const key = keyAccount(account);
  const haystack = `${project} ${account} ${text}`.toLowerCase();
  if (!key) return false;
  if (hiddenAccounts.has(key)) return false;
  if (hardHiddenWords.some((word) => haystack.includes(word))) return false;
  if (!strongSignal && hiddenWords.some((word) => haystack.includes(word))) return false;
  if (positiveWords.some((word) => haystack.includes(word))) return true;
  return strongSignal && !hiddenWords.some((word) => haystack.includes(word));
}
